### ISSUE TITLE
ModuleNotFoundError: No module named 'ldm.models.diffusion'

### ISSUE THREAD

**Issue by scottcali** [kealiu/ComfyUI-Zero123-Porting#4]
Traceback (most recent call last):
  File "ComfyUI\.\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "ComfyUI\custom_nodes\ComfyUI-Zero123-Porting\__init__.py", line 6, in <module>
    from zero123_nodes import Zero123, Zero123Preprocess
  File "ComfyUI\custom_nodes\ComfyUI-Zero123-Porting\zero123_nodes.py", line 6, in <module>
    from zero123 import init_model, predict_cam
  File "ComfyUI\custom_nodes\ComfyUI-Zero123-Porting\zero123.py", line 8, in <module>
    from ldm.models.diffusion.ddim import DDIMSampler
ModuleNotFoundError: No module named 'ldm.models.diffusion'

Cannot import ComfyUI\custom_nodes\ComfyUI-Zero123-Porting module for custom nodes: No module named 'ldm.models.diffusion'

**Comment by kealiu** [comment]
whieh python version did you use? and can you print the `python` system environment of `sys.path`.

from https://github.com/kealiu/ComfyUI-Zero123-Porting/blob/802e6c0302abfea5c6a32abf5e3f3822d28cad46/__init__.py#L4, the code will make `ComfyUI-Zero123-Porting` load `ldm.models.diffusion` from current directory.

but seems this not work. so, some thing wrong with the python module search path configuration.
